module Directions
  EAST = 'E'
  WEST = 'W'
  NORTH = 'N'
  SOUTH = 'S'
  ANTI_CLOCKWISE = 'L'
  CLOCKWISE = 'R'
  ANTI_CLOCKWISE_DIRECTION_CONVERSION = {NORTH => WEST, EAST => NORTH, WEST=> SOUTH, SOUTH=> EAST}
  CLOCKWISE_DIRECTION_CONVERSION = {NORTH=> EAST, EAST=> SOUTH, WEST=> NORTH, SOUTH=> WEST}
end